def dico_matin():
    dico_prompt = {
        "dis bonjour à tout le monde et souhaite leur de passer une bonne journée" : 1, 
        "pause leur une question sur leur activité de la journée et dis bonjour" : 2, 
        "demande comment vas être leur week-end et dis bonjour" : 3, 
        "demande comment se passe leur week-end et dis bonjour" : 4, 
        "demande leur comment se passe leur semaine et dis bonjour" : 5,
        "demande leur se qu'il pense comment va être leur journée" : 6,
        "souhaite leur bonne chance pour leur journée" : 7,
        "souhaite leur bonne chance pour leur journée de travail" : 8,
        "propose leur une activité pour leur week-end et dis bonjour": 9,
        "demande leur s'ils ont des projets pour la semaine prochaine et dis bonjour": 10,
        "invite les à partager leur expérience récente et dis bonjour": 11,
        "suggère une sortie pour leur week-end et dis bonjour": 12,
        "demande leur s'ils ont des plans pour la journée et dis bonjour": 13,
        }
    return dico_prompt

def dico_soir():
    dico_prompt = {
        "dis bonsoir à tout le monde et souhaite-leur une excellente soirée": 1,
        "pose-leur une question sur leur journée": 2,
        "demande-leur comment s'est déroulée leur journée": 3,
        "demande-leur s'ils ont des projets pour la soirée": 4,
        "demande-leur ce qu'ils ont prévu pour le dîner": 5,
        "souhaite-leur une agréable soirée": 6,
        "propose-leur une activité de détente pour ce soir": 7,
        "invite-les à partager un moment ensemble à discuter sur twitter": 8,
        "rappelle-leur de se reposer et de prendre soin d'eux": 9,
        "propose-leur une idée pour se relaxer": 10,
        "demande-leur comment ils comptent terminer leur journée en beauté": 11,
        "apporte leur un soutien pour leur dure journée": 12,
        "soit gentille avec eux et souhaite leur de passez un exelente soirée": 13,
        "demande-leur à quelle heure vont-ils se coucher": 14,
        "encourage-les à profiter de leur soirée": 15,
        "Souhaite leur un exelent week-end": 16,
        "demande leur ce qu'il compte faire ce week-end": 17,
        "souhaite leur bonne chance pour demain qui est un lundi donc la reprise du travail": 18,
        }
    return dico_prompt

def dico_nuit():
    dico_bonne_nuit = {
        "dis bonne nuit à tout le monde et souhaite-leur de beaux rêves": 1,
        "pose-leur une question sur leur journée et souhaite-leur une bonne nuit": 2,
        "souhaite-leur une agréable nuit": 3,
        "demande-leur s'ils ont des projets pour demain et souhaite-leur une bonne nuit": 4,
        "souhaite-leur une douce nuit et d'être fort pour le lendemain": 5,
        "souhaite-leur une excellente nuit et de faire de beaux rêves": 6,
        "propose-leur une activité relaxante avant de dormir": 7,
        "invite-les à se détendre et à se reposer pour bien dormir": 8,
        "rappelle-leur l'importance de bien se reposer et de prendre soin d'eux": 9,
        "suggère-leur de faire une pause avec les écrans avant de dormir": 10,
        "propose-leur une idée pour favoriser leur sommeil": 11,
        "demande-leur comment ils comptent terminer leur journée en beauté et souhaite-leur une bonne nuit": 12,
        "encourage-les à profiter d'une bonne nuit de sommeil": 13,
        "Souhaite-leur un excellent repos et un réveil en pleine forme": 14,
        "demande-leur ce qu'ils aimeraient faire demain et souhaite-leur une douce nuit": 15,
        "suggère-leur de se déconnecter un peu des écrans": 16,
        "suggère-leur de se déconnecter un peu des jeux vidéos si ils sont dessus": 17,
        "je rêverais de pouvoir un jour voir le ciel étoilé ça doit être magnifique": 18,
        }
    return dico_bonne_nuit


def dico_phrases():
    dico_phrases = {
        "Quel est ton film préféré et pourquoi ?": 1,
        "Quel est ton livre préféré et pourquoi ?": 2,
        "Quelle est ta chanson préférée et pourquoi ?": 3,
        "Quelle est ta couleur préférée et pourquoi ?": 4,
        "Quel est ton plat préféré et pourquoi ?": 5,
        "Quelle est ta saison préférée et pourquoi ?": 6,
        "Quel est ton animal préféré et pourquoi ?": 7,
        "Quelle est ta destination de voyage préférée et pourquoi ?": 8,
        "Quel est ton sport préféré et pourquoi ?": 9,
        "Quel est ton hobby préféré et pourquoi ?": 10,
        "Quel est ton jeu vidéo préféré et pourquoi ?": 11,
        "Quelle est ta série TV préférée et pourquoi ?": 12,
        "Quelle est ta citation préférée et pourquoi ?": 13,
        "Quel est ton événement historique préféré et pourquoi ?": 14,
        "Quel est ton super-héros préféré et pourquoi ?": 15,
        "Quel est ton personnage de fiction préféré et pourquoi ?": 16,
        "Quel est ton acteur/actrice préféré(e) et pourquoi ?": 17,
        "Quel est ton musée préféré et pourquoi ?": 18,
        "Quel est ton monument préféré et pourquoi ?": 19,
        "Quelle est ta boisson préférée et pourquoi ?": 20,
        "Quel est ton événement sportif préféré et pourquoi ?": 21,
        "Quelle est ta fête préférée et pourquoi ?": 22,
        "Quel est ton instrument de musique préféré et pourquoi ?": 23,
        "Quel est ton endroit préféré pour te détendre et pourquoi ?": 24,
        "Quelle est ta période de l'histoire préférée et pourquoi ?": 25,
        "Quelle est ta marque de vêtements préférée et pourquoi ?": 26,
        "Quelle est ta marque de voiture préférée et pourquoi ?": 27,
        "Quel est ton personnage de dessin animé préféré et pourquoi ?": 28,
        "Quel est ton genre de musique préféré et pourquoi ?": 29,
        "Quelle est ta qualité préférée chez une personne et pourquoi ?": 30,
        "Quel est ton défaut préféré chez une personne et pourquoi ?": 31,
        "Quelle est ta valeur préférée et pourquoi ?": 32,
        "Quel est ton paysage naturel préféré et pourquoi ?": 33,
        "Quelle est ta pièce préférée dans une maison et pourquoi ?": 34,
        "Quel est ton proverbe préféré et pourquoi ?": 35,
        "Quelle est ta matière scolaire préférée et pourquoi ?": 36,
        "Quelle est ta profession préférée et pourquoi ?": 37,
        "Quel est ton élément naturel préféré et pourquoi ?": 38,
        "Quelle est ta croyance spirituelle préférée et pourquoi ?": 39,
        "Quel est ton réseau social préféré et pourquoi ?": 40,
        "Quelle est ta méthode de relaxation préférée et pourquoi ?": 41,
        "Quel est ton logiciel préféré et pourquoi ?": 42,
        "Quel est ton navigateur web préféré et pourquoi ?": 43,
        "Quelle est ta fonctionnalité préférée sur un smartphone et pourquoi ?": 44,
        "Quel est ton événement technologique préféré et pourquoi ?": 45,
        "Quel est ton site web préféré et pourquoi ?": 46,
        "Quelle est ta source d'information préférée et pourquoi ?": 47,
        "Quelle est ta source d'inspiration préférée et pourquoi ?": 48,
        "Quelle est ta méthode de résolution de problème préférée et pourquoi ?": 49,
        "Quel est ton moyen de transport préféré et pourquoi ?": 50,
        "Quel est ton festival préféré et pourquoi ?": 51,
        "Quelle est ta période de l'année préférée et pourquoi ?": 52,
        "Quel est ton concept philosophique préféré et pourquoi ?": 53,
        "Quelle est ta découverte scientifique préférée et pourquoi ?": 54,
        "Quel est ton élément architectural préféré et pourquoi ?": 55,
        "Quelle est ta pièce de mobilier préférée et pourquoi ?": 56,
        "Quel est ton instrument de cuisine préféré et pourquoi ?": 57,
        "Quelle est ta tradition culturelle préférée et pourquoi ?": 58,
        "Quel est ton festival de musique préféré et pourquoi ?": 59,
        "Quelle est ta montagne préférée et pourquoi ?": 60,
        "Quel est ton phénomène naturel préféré et pourquoi ?": 61,
        "Quelle est ta météo préférée et pourquoi ?": 62,
        "Quel est ton jeu de société préféré et pourquoi ?": 63,
        "Quelle est ta pièce de théâtre préférée et pourquoi ?": 64,
        "Quel est ton genre de danse préféré et pourquoi ?": 65,
        "Quelle est ta saveur de glace préférée et pourquoi ?": 66,
        "Quel est ton arbre préféré et pourquoi ?": 67,
        "Quelle est ta fleur préférée et pourquoi ?": 68,
        "Quel est ton paysage urbain préféré et pourquoi ?": 69,
        "Quelle est ta mode de communication préférée et pourquoi ?": 70,
        "Quel est ton modèle de téléphone préféré et pourquoi ?": 71,
        "Quelle est ta fonctionnalité de gadget préférée et pourquoi ?": 72,
        "Quel est ton accessoire vestimentaire préféré et pourquoi ?": 73,
        "Quelle est ta forme artistique préférée et pourquoi ?": 74,
        "Quel est ton style architectural préféré et pourquoi ?": 75,
        "Quelle est ta période musicale préférée et pourquoi ?": 76,
        }
    return dico_phrases
    
def dico_question_anime():
    dico_anime = {
        "Quel est ton anime préféré et pourquoi ?": 1,
        "As-tu déjà assisté à une convention d'anime ?": 2,
        "Quel est ton personnage d'anime préféré et pourquoi ?": 3,
        "Quel est l'anime que tu recommanderais à quelqu'un qui débute ?": 4,
        "Comment as-tu découvert les animes ?": 5,
        "Quel genre d'anime préfères-tu ?": 6,
        "As-tu déjà lu des mangas ? Si oui, lequel préfères-tu ?": 7,
        "Quelle est ta scène d'anime préférée ?": 8,
        "As-tu un opening ou un ending d'anime que tu écoutes en boucle ?": 9,
        "Quel anime t'a le plus marqué émotionnellement ?": 10,
        "As-tu déjà essayé de dessiner des personnages d'anime ?": 11,
        "Y a-t-il un anime que tu aimerais voir adapté en film live-action ?": 12,
        "Quel est ton studio d'animation japonais préféré et pourquoi ?": 13,
        "Si tu pouvais vivre dans l'univers d'un anime, lequel choisirais-tu ?": 14,
        "Quel est le dernier anime que tu as regardé et qu'en as-tu pensé ?": 15,
        }
    return dico_anime

def dico_nom_anime():
    dico_anime = {
        "Naruto": 1,
        "One Piece": 2,
        "DBZ": 3,
        "Death Note": 4,
        "SNK": 5,
        "FMAB": 6,
        "MHA": 7,
        "kny": 8,
        "One Punch Man": 9,
        "Tokyo Ghoul": 10,
        "Sword Art Online": 11,
        "Hunter x Hunter": 12,
        "Fairy Tail": 13,
        "Bleach": 14,
        "Cowboy Bebop": 15,
        "Code Geass": 16,
        "Evangelion": 17,
        "Black Clover": 18,
        "Naruto Shippuden": 19,
        "JoJo": 20,
        "Hell's Paradise": 21,
        "Steins;Gate": 22,
        "Soul Eater": 23,
        "Dragon Ball": 24,
        "The Promised Neverland": 25,
        "Overlord": 26,
        "Mob Psycho 100": 27,
        "Gurren Lagann": 28,
        "Fate/stay night": 29,
        "Fruits Basket": 30,
        "Yu Yu Hakusho": 31,
        "Rent a girldriend": 32,
        "No Game No Life": 33,
        "Clannad": 34,
        "Inuyasha": 35,
        "Parasyte": 36,
        "classroom of the eilte": 37,
        "Assassination Classroom": 38,
        "Darling in the Franxx": 39,
        "The Seven Deadly Sins": 40,
        "Danganronpa": 41,
        "Your name": 42,
        "Toradora": 43,
        "Violet Evergarden": 44,
        "Berserk": 45,
        "Ghost in the Shell": 46,
        "Re:Zero": 47,
        "Vinland saga": 48,
        "Les carnets de l'apoticaire": 49,
        "Dr Stone": 50,
        "Oshi no Ko": 51,
        "Frieren": 52,
        "Kaguya-sama": 53,
        "Love is war": 54,
        "Quintessential Quintuplets": 55,
        "Gotobun": 56,
        }
    return dico_anime
    
def dico_question_anime_name():
    dico_question_name_anime = {
        "Quelle est ton personnage prééré dans {anime} et pourquoi ?": 1,
        "Quel est ton arc prééré dans {anime} et pourquoi ?": 2,
        "Quel est ton moment le plus mémorable dans {anime} et pourquoi ?": 3,
        "Quel est ton opening/ending prééré dans {anime} et pourquoi ?": 4,
        "Quel aspect de {anime} t'a le plus marqué et pourquoi ?": 5,
        "Si tu pouvais vivre dans l'univers de {anime}, quel personnage serais-tu ?": 6,
        "Quel pouvoir ou capacité de {anime} aimerais-tu posséder et pourquoi ?": 7,
        "Quel est ton épisode prééré de {anime} et pourquoi ?": 8,
        "Quel personnage de {anime} aimerais-tu rencontrer dans la vraie vie et pourquoi ?": 9,
        "Quelle leçon as-tu apprise de {anime} ?": 10,
        "Quel est ton lieu prééré dans {anime} et pourquoi ?": 11,
        "Si tu pouvais changer une chose dans {anime}, que serait-ce ?": 12,
        "Quelle est la meilleure rivalité dans {anime} et pourquoi ?": 13,
        "Quel est le meilleur combat dans {anime} et pourquoi ?": 14,
        "Quel personnage de {anime} as-tu le plus de mal à comprendre et pourquoi ?": 15,
        "Quel personnage de {anime} est le plus sous-estimé à ton avis ?": 16,
        "Si tu pouvais être transporté dans l'histoire de {anime}, que changerais-tu ?": 17,
        "Quelle est la morale la plus importante dans {anime} ?": 18,
        "Quel aspect de l'histoire de {anime} t'a le plus inspiré et pourquoi ?": 19,
        "Quelle est ta réaction préférée de {anime} et pourquoi ?": 20,
        "Si tu étais un personnage de {anime}, comment imagines-tu ton développement ?": 21,
        "Quel événement de {anime} t'a le plus surpris et pourquoi ?": 22,
        "Si tu devais réécrire la fin de {anime}, comment la changerais-tu ?": 23,
        "Quelle est la meilleure relation entre personnages dans {anime} et pourquoi ?": 24,
        "Quel est le thème principal de {anime} selon toi et pourquoi ?": 25,
        "Si tu avais une journée à passer avec les personnages de {anime}, que ferais-tu ?": 26,
        "Quel objet de {anime} aimerais-tu posséder dans la vie réelle ?": 27,
        "Si tu pouvais être ami avec un personnage de {anime}, lequel choisirais-tu et pourquoi ?": 28,
        "Quel personnage de {anime} ressemble le plus à ta personnalité et pourquoi ?": 29,
        "Si tu pouvais changer un événement de {anime}, lequel changerait-ce et pourquoi ?": 30,
        "Quel est le message le plus profond que tu as tiré de {anime} ?": 31,
        "Quel personnage de {anime} admires-tu le plus et pourquoi ?": 32,
        "Quel aspect de {anime} te fait le plus réfléchir sur la vie ?": 33,
        "Si {anime} était adapté en film live-action, quel acteur verrais-tu jouer ton personnage préféré ?": 34,
        "Quelle est la scène la plus émouvante de {anime} selon toi et pourquoi ?": 35,
        "Si tu devais décrire {anime} en un mot, quel serait-il ?": 36,
        "Quel personnage de {anime} as-tu le plus de mal à supporter et pourquoi ?": 37,
        "Quel est l'aspect de l'animation de {anime} qui te fascine le plus et pourquoi ?": 38,
        "Si tu devais recommander {anime} à quelqu'un qui n'a jamais regardé d'anime, que dirais-tu ?": 39,
        "Quel événement de {anime} aurais-tu aimé vivre en personne ?": 40,
        "Quel aspect de {anime} te donne le plus envie d'explorer son univers ?": 41,
        "Si tu devais écrire une suite à {anime}, quelle serait l'histoire ?": 42,
        "Quel personnage secondaire de {anime} mériterait sa propre série ?": 43,
        "Quelle est la réplique la plus mémorable de {anime} pour toi ?": 44,
        "Quel élément de l'intrigue de {anime} te semble le plus original et pourquoi ?": 45,
        "Si tu pouvais changer le design d'un personnage de {anime}, lequel choisirais-tu ?": 46,
        "Quelle est la plus grande leçon de vie que tu as apprise de {anime} ?": 47,
        "Si tu pouvais être transporté dans un autre monde comme dans {anime}, que ferais-tu en premier ?": 48,
        "Quel personnage de {anime} aurais-tu aimé être et pourquoi ?": 49,
        "Si tu devais éliminer un personnage de {anime}, lequel serait-ce et pourquoi ?": 50,
        }
    return dico_question_name_anime